modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/SnakerBone/AzcrayCore/issues"
[[mods]]
modId="azcray"
version="${file.jarVersion}"
displayName="Azcray Core"
updateJSONURL="https://github.com/SnakerBone/AzcrayCore/blob/main/updates.json"
displayURL="https://github.com/SnakerBone/AzcrayCore"
logoFile="icon.png"
authors="SnakerBone"
description='Core Functionality For Azcray.'
[[dependencies.azcray]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.azcray]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
