modLoader = "javafml"
loaderVersion = "[36,)"
license = "NONE"
issueTrackerURL = "https://github.com/SnakerBone/AzcrayCore/issues"

[[mods]]
modId = "azcray"
version = "${file.jarVersion}"
displayName = "Azcray Core"
displayURL = "https://github.com/SnakerBone/AzcrayCore"
logoFile = "NONE"
authors = "SnakerBone"
description = "Azcray Core"

[[dependencies.azcray]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.azcray]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
